#!/usr/bin/env bash
# Build a signed arm64 release APK and publish it to the website for direct download.
# Usage: ./scripts/publish_android.sh   (runnable from anywhere)
#
# Steps: builds + signs the arm64-v8a release APK (signing comes from android/key.properties),
# copies it to website/public/bantera.apk, and stamps the version the site shows into
# website/src/lib/android-release.ts. Afterwards, commit + push those two files in ./website.
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WEBSITE="$APP_DIR/../website"

[ -f "$APP_DIR/android/key.properties" ] || { echo "ERROR: android/key.properties missing — release signing not configured." >&2; exit 1; }
[ -d "$WEBSITE/public" ] || { echo "ERROR: website not found at $WEBSITE" >&2; exit 1; }

cd "$APP_DIR"

FULL="$(grep '^version:' pubspec.yaml | sed 's/version:[[:space:]]*//')"
NAME="${FULL%%+*}"
BUILD="${FULL##*+}"

echo "Building signed arm64 release APK v$NAME ($BUILD)..."
# Remove any stale split APK so a failed build can't leave us copying an old file.
rm -f build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
flutter build apk --release --split-per-abi --target-platform android-arm64

cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk "$WEBSITE/public/bantera.apk"

cat > "$WEBSITE/src/lib/android-release.ts" <<EOF
// Auto-generated by app/scripts/publish_android.sh — do not edit by hand.
export const androidRelease = { version: '$NAME', build: $BUILD } as const;
EOF

SIZE="$(du -h "$WEBSITE/public/bantera.apk" | cut -f1)"
echo "✓ Published bantera.apk v$NAME ($BUILD) — $SIZE"
echo "  -> $WEBSITE/public/bantera.apk"
echo "  -> $WEBSITE/src/lib/android-release.ts"
echo "Next: commit & push public/bantera.apk + src/lib/android-release.ts in ./website to deploy."
